# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Roastme' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Roastme
  pod 'Alamofire', '~> 4.4.0'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'SideMenu', '~> 2.3'
  

  target 'RoastmeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoastmeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
