# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roastserv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roastmeuser',
            old_name='saltInventory',
            new_name='seasoning',
        ),
        migrations.RemoveField(
            model_name='roastmeuser',
            name='sauceInventory',
        ),
    ]
