# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roastserv', '0003_auto_20170326_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roast',
            name='roastComment',
        ),
        migrations.AddField(
            model_name='roastcomment',
            name='roast',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roastserv.Roast'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roast',
            name='picture',
            field=models.ImageField(upload_to='roast'),
        ),
    ]
