# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roastserv', '0005_auto_20170401_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='roastcomment',
            name='content_raw',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
