# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roastserv', '0006_roastcomment_content_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='roastcomment',
            old_name='salt',
            new_name='downvotes',
        ),
        migrations.AddField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roastserv.RoastComment'),
        ),
    ]
